# Firebase konfiguration för AktivitusFinans
# Denna fil innehåller de nya Firebase-credentials från det nya projektet

[firebase]
apiKey = "AIzaSyCWgow5O8sklURfyJX2pf-MiltKlANMdrg"
authDomain = "aktivitusfinans.firebaseapp.com"
databaseURL = "https://aktivitusfinans-default-rtdb.europe-west1.firebasedatabase.app"
projectId = "aktivitusfinans"
storageBucket = "aktivitusfinans.firebasestorage.app"
messagingSenderId = "684415073315"
appId = "1:684415073315:web:262b76342bf4f320038596"

# För lokal utveckling - kopiera dessa till .env.local
[env_variables]
FIREBASE_API_KEY = "AIzaSyCWgow5O8sklURfyJX2pf-MiltKlANMdrg"
FIREBASE_AUTH_DOMAIN = "aktivitusfinans.firebaseapp.com"
FIREBASE_DATABASE_URL = "https://aktivitusfinans-default-rtdb.europe-west1.firebasedatabase.app"
FIREBASE_PROJECT_ID = "aktivitusfinans"
FIREBASE_STORAGE_BUCKET = "aktivitusfinans.firebasestorage.app"
FIREBASE_MESSAGING_SENDER_ID = "684415073315"
FIREBASE_APP_ID = "1:684415073315:web:262b76342bf4f320038596"
